export const SLICE_NAME_MULTIMEDIA = "MULTIMEDIA"
export const MULTIMEDIA_ACTIONS = {
    MULTIMEDIA: `${SLICE_NAME_MULTIMEDIA}_MULTIMEDIA`,
    LIKE: `${SLICE_NAME_MULTIMEDIA}_LIKE`,
    GET_LIKE: `${SLICE_NAME_MULTIMEDIA}_GET-LIKE`,
    GET_MULTIMEDIA_BY_USER: `${SLICE_NAME_MULTIMEDIA}_GET_MULTIMEDIA_BY_USER`
} 

